// Code generated by logcopter-gen; DO NOT EDIT.

package mcp

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.sqleton.cmd.sqleton.cmds.mcp")
