// Code generated by logcopter-gen; DO NOT EDIT.

package codegen

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.sqleton.pkg.codegen")
